package com.fal701.block.MediumAshlar;

import com.fal701.Rhumtopia;
import com.fal701.block.Z_custom.*;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.*;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class MediumAshlar {
    public static final Block BLACK_GRANITE = registerBlock("black_granite", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_STAIRS = registerBlock("black_granite_stairs", new WcStairs(BLACK_GRANITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_SLAB = registerBlock("black_granite_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_WALL = registerBlock("black_granite_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_FENCE = registerBlock("black_granite_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_HOPPER = registerBlock("black_granite_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_TIP = registerBlock("black_granite_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_ARROW_SLIT = registerBlock("black_granite_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_ARROW_SLIT_WINDOW = registerBlock("black_granite_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block BLACK_GRANITE_ARROW_SLIT_ORNATE = registerBlock("black_granite_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE = registerBlock("winterfell_granite", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_STAIRS = registerBlock("winterfell_granite_stairs", new WcStairs(WINTERFELL_GRANITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_SLAB = registerBlock("winterfell_granite_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_WALL = registerBlock("winterfell_granite_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_FENCE = registerBlock("winterfell_granite_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_HOPPER = registerBlock("winterfell_granite_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_TIP = registerBlock("winterfell_granite_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_ARROW_SLIT = registerBlock("winterfell_granite_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_ARROW_SLIT_WINDOW = registerBlock("winterfell_granite_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WINTERFELL_GRANITE_ARROW_SLIT_ORNATE = registerBlock("winterfell_granite_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE = registerBlock("green_grey_granite", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_STAIRS = registerBlock("green_grey_granite_stairs", new WcStairs(GREEN_GREY_GRANITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_SLAB = registerBlock("green_grey_granite_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_WALL = registerBlock("green_grey_granite_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_FENCE = registerBlock("green_grey_granite_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_HOPPER = registerBlock("green_grey_granite_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_TIP = registerBlock("green_grey_granite_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_ARROW_SLIT = registerBlock("green_grey_granite_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_ARROW_SLIT_WINDOW = registerBlock("green_grey_granite_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREEN_GREY_GRANITE_ARROW_SLIT_ORNATE = registerBlock("green_grey_granite_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE = registerBlock("grey_granite", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_STAIRS = registerBlock("grey_granite_stairs", new WcStairs(GREY_GRANITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_SLAB = registerBlock("grey_granite_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_WALL = registerBlock("grey_granite_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_FENCE = registerBlock("grey_granite_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_HOPPER = registerBlock("grey_granite_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_TIP = registerBlock("grey_granite_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_ARROW_SLIT = registerBlock("grey_granite_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_ARROW_SLIT_WINDOW = registerBlock("grey_granite_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block GREY_GRANITE_ARROW_SLIT_ORNATE = registerBlock("grey_granite_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE = registerBlock("white_granite", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_STAIRS = registerBlock("white_granite_stairs", new WcStairs(WHITE_GRANITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_SLAB = registerBlock("white_granite_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_WALL = registerBlock("white_granite_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_FENCE = registerBlock("white_granite_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_HOPPER = registerBlock("white_granite_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_TIP = registerBlock("white_granite_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_ARROW_SLIT = registerBlock("white_granite_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_ARROW_SLIT_WINDOW = registerBlock("white_granite_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block WHITE_GRANITE_ARROW_SLIT_ORNATE = registerBlock("white_granite_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE = registerBlock("pink_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_STAIRS = registerBlock("pink_sandstone_stairs", new WcStairs(PINK_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_SLAB = registerBlock("pink_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_WALL = registerBlock("pink_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_FENCE = registerBlock("pink_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_HOPPER = registerBlock("pink_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_TIP = registerBlock("pink_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_ARROW_SLIT = registerBlock("pink_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("pink_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block PINK_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("pink_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK = registerBlock("kl_dun_brick", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_STAIRS = registerBlock("kl_dun_brick_stairs", new WcStairs(KL_DUN_BRICK.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_SLAB = registerBlock("kl_dun_brick_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_WALL = registerBlock("kl_dun_brick_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_FENCE = registerBlock("kl_dun_brick_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_HOPPER = registerBlock("kl_dun_brick_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_TIP = registerBlock("kl_dun_brick_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_ARROW_SLIT = registerBlock("kl_dun_brick_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_ARROW_SLIT_WINDOW = registerBlock("kl_dun_brick_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block KL_DUN_BRICK_ARROW_SLIT_ORNATE = registerBlock("kl_dun_brick_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE = registerBlock("coarse_red_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_STAIRS = registerBlock("coarse_red_sandstone_stairs", new WcStairs(COARSE_RED_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_SLAB = registerBlock("coarse_red_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_WALL = registerBlock("coarse_red_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_FENCE = registerBlock("coarse_red_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_HOPPER = registerBlock("coarse_red_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_TIP = registerBlock("coarse_red_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_ARROW_SLIT = registerBlock("coarse_red_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("coarse_red_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_RED_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("coarse_red_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));

    public static final Block RED_SANDSTONE = registerBlock("red_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_STAIRS = registerBlock("red_sandstone_stairs", new WcStairs(RED_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_SLAB = registerBlock("red_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_WALL = registerBlock("red_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_FENCE = registerBlock("red_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_HOPPER = registerBlock("red_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_TIP = registerBlock("red_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_ARROW_SLIT = registerBlock("red_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("red_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block RED_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("red_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE = registerBlock("coarse_dark_red_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_STAIRS = registerBlock("coarse_dark_red_sandstone_stairs", new WcStairs(COARSE_DARK_RED_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_SLAB = registerBlock("coarse_dark_red_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_WALL = registerBlock("coarse_dark_red_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_FENCE = registerBlock("coarse_dark_red_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_HOPPER = registerBlock("coarse_dark_red_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_TIP = registerBlock("coarse_dark_red_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_ARROW_SLIT = registerBlock("coarse_dark_red_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("coarse_dark_red_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block COARSE_DARK_RED_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("coarse_dark_red_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE = registerBlock("dark_red_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_STAIRS = registerBlock("dark_red_sandstone_stairs", new WcStairs(DARK_RED_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_SLAB = registerBlock("dark_red_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_WALL = registerBlock("dark_red_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_FENCE = registerBlock("dark_red_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_HOPPER = registerBlock("dark_red_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_TIP = registerBlock("dark_red_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_ARROW_SLIT = registerBlock("dark_red_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("dark_red_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DARK_RED_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("dark_red_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE = registerBlock("oldtown_granite", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_STAIRS = registerBlock("oldtown_granite_stairs", new WcStairs(OLDTOWN_GRANITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_SLAB = registerBlock("oldtown_granite_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_WALL = registerBlock("oldtown_granite_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_FENCE = registerBlock("oldtown_granite_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_HOPPER = registerBlock("oldtown_granite_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_TIP = registerBlock("oldtown_granite_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_ARROW_SLIT = registerBlock("oldtown_granite_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_ARROW_SLIT_WINDOW = registerBlock("oldtown_granite_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block OLDTOWN_GRANITE_ARROW_SLIT_ORNATE = registerBlock("oldtown_granite_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK = registerBlock("arbor_brick", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_STAIRS = registerBlock("arbor_brick_stairs", new WcStairs(ARBOR_BRICK.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_SLAB = registerBlock("arbor_brick_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_WALL = registerBlock("arbor_brick_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_FENCE = registerBlock("arbor_brick_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_HOPPER = registerBlock("arbor_brick_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_TIP = registerBlock("arbor_brick_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_ARROW_SLIT = registerBlock("arbor_brick_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_ARROW_SLIT_WINDOW = registerBlock("arbor_brick_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block ARBOR_BRICK_ARROW_SLIT_ORNATE = registerBlock("arbor_brick_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE = registerBlock("vivid_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_STAIRS = registerBlock("vivid_sandstone_stairs", new WcStairs(VIVID_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_SLAB = registerBlock("vivid_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_WALL = registerBlock("vivid_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_FENCE = registerBlock("vivid_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_HOPPER = registerBlock("vivid_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_TIP = registerBlock("vivid_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_ARROW_SLIT = registerBlock("vivid_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("vivid_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("vivid_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE = registerBlock("vivid_mossy_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE_STAIRS = registerBlock("vivid_mossy_sandstone_stairs", new WcStairs(VIVID_MOSSY_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE_SLAB = registerBlock("vivid_mossy_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE_WALL = registerBlock("vivid_mossy_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE_FENCE = registerBlock("vivid_mossy_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE_HOPPER = registerBlock("vivid_mossy_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_MOSSY_SANDSTONE_TIP = registerBlock("vivid_mossy_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE = registerBlock("monochrome_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_STAIRS = registerBlock("monochrome_sandstone_stairs", new WcStairs(MONOCHROME_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_SLAB = registerBlock("monochrome_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_WALL = registerBlock("monochrome_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_FENCE = registerBlock("monochrome_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_HOPPER = registerBlock("monochrome_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_TIP = registerBlock("monochrome_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_ARROW_SLIT = registerBlock("monochrome_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("monochrome_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("monochrome_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE = registerBlock("monochrome_mossy_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE_STAIRS = registerBlock("monochrome_mossy_sandstone_stairs", new WcStairs(MONOCHROME_MOSSY_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE_SLAB = registerBlock("monochrome_mossy_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE_WALL = registerBlock("monochrome_mossy_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE_FENCE = registerBlock("monochrome_mossy_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE_HOPPER = registerBlock("monochrome_mossy_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_MOSSY_SANDSTONE_TIP = registerBlock("monochrome_mossy_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE = registerBlock("vivid_dark_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_STAIRS = registerBlock("vivid_dark_sandstone_stairs", new WcStairs(VIVID_DARK_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_SLAB = registerBlock("vivid_dark_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_WALL = registerBlock("vivid_dark_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_FENCE = registerBlock("vivid_dark_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_HOPPER = registerBlock("vivid_dark_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_TIP = registerBlock("vivid_dark_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_ARROW_SLIT = registerBlock("vivid_dark_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("vivid_dark_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block VIVID_DARK_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("vivid_dark_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE = registerBlock("monochrome_dark_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_STAIRS = registerBlock("monochrome_dark_sandstone_stairs", new WcStairs(MONOCHROME_DARK_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_SLAB = registerBlock("monochrome_dark_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_WALL = registerBlock("monochrome_dark_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_FENCE = registerBlock("monochrome_dark_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_HOPPER = registerBlock("monochrome_dark_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_TIP = registerBlock("monochrome_dark_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_ARROW_SLIT = registerBlock("monochrome_dark_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("monochrome_dark_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block MONOCHROME_DARK_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("monochrome_dark_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE = registerBlock("desert_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_STAIRS = registerBlock("sandstone_stairs", new WcStairs(DESERT_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_SLAB = registerBlock("desert_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_WALL = registerBlock("desert_sandstone_brick_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_FENCE = registerBlock("desert_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_HOPPER = registerBlock("desert_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_TIP = registerBlock("desert_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_ARROW_SLIT = registerBlock("desert_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("desert_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DESERT_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("desert_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE = registerBlock("dorne_dark_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_STAIRS = registerBlock("dorne_dark_sandstone_stairs", new WcStairs(DORNE_DARK_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_SLAB = registerBlock("dorne_dark_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_WALL = registerBlock("dorne_dark_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_FENCE = registerBlock("dorne_dark_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_HOPPER = registerBlock("dorne_dark_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_TIP = registerBlock("dorne_dark_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_ARROW_SLIT = registerBlock("dorne_dark_sandstone_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_ARROW_SLIT_WINDOW = registerBlock("dorne_dark_sandstone_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DARK_SANDSTONE_ARROW_SLIT_ORNATE = registerBlock("dorne_dark_sandstone_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE = registerBlock("dorne_mossy_dark_sandstone", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE_STAIRS = registerBlock("dorne_mossy_dark_sandstone_stairs", new WcStairs(DORNE_MOSSY_DARK_SANDSTONE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE_SLAB = registerBlock("dorne_mossy_dark_sandstone_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE_WALL = registerBlock("dorne_mossy_dark_sandstone_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE_FENCE = registerBlock("dorne_mossy_dark_sandstone_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE_HOPPER = registerBlock("dorne_mossy_dark_sandstone_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_DARK_SANDSTONE_TIP = registerBlock("dorne_mossy_dark_sandstone_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA = registerBlock("dorne_dull_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_STAIRS = registerBlock("dorne_dull_terracotta_stairs", new WcStairs(DORNE_DULL_TERRACOTTA.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_SLAB = registerBlock("dorne_dull_terracotta_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_WALL = registerBlock("dorne_dull_terracotta_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_FENCE = registerBlock("dorne_dull_terracotta_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_HOPPER = registerBlock("dorne_dull_terracotta_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_TIP = registerBlock("dorne_dull_terracotta_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_ARROW_SLIT = registerBlock("dorne_dull_terracotta_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_ARROW_SLIT_WINDOW = registerBlock("dorne_dull_terracotta_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_DULL_TERRACOTTA_ARROW_SLIT_ORNATE = registerBlock("dorne_dull_terracotta_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA = registerBlock("dorne_light_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_STAIRS = registerBlock("dorne_light_terracotta_stairs", new WcStairs(DORNE_LIGHT_TERRACOTTA.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_SLAB = registerBlock("dorne_light_terracotta_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_WALL = registerBlock("dorne_light_terracotta_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_FENCE = registerBlock("dorne_light_terracotta_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_HOPPER = registerBlock("dorne_light_terracotta_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_TIP = registerBlock("dorne_light_terracotta_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_ARROW_SLIT = registerBlock("dorne_light_terracotta_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_ARROW_SLIT_WINDOW = registerBlock("dorne_light_terracotta_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_LIGHT_TERRACOTTA_ARROW_SLIT_ORNATE = registerBlock("dorne_light_terracotta_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA = registerBlock("dorne_mossy_light_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA_STAIRS = registerBlock("dorne_mossy_light_terracotta_stairs", new WcStairs(DORNE_MOSSY_LIGHT_TERRACOTTA.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA_SLAB = registerBlock("dorne_mossy_light_terracotta_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA_WALL = registerBlock("dorne_mossy_light_terracotta_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA_FENCE = registerBlock("dorne_mossy_light_terracotta_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA_HOPPER = registerBlock("dorne_mossy_light_terracotta_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block DORNE_MOSSY_LIGHT_TERRACOTTA_TIP = registerBlock("dorne_mossy_light_terracotta_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA = registerBlock("terracotta", new Block(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_STAIRS = registerBlock("terracotta_stairs", new WcStairs(TERRACOTTA.getDefaultState(), FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_SLAB = registerBlock("terracotta_slab", new SlabBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_WALL = registerBlock("terracotta_wall", new WcWall(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_FENCE = registerBlock("terracotta_fence", new WcFence(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_HOPPER = registerBlock("terracotta_hopper", new WcHopper(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_TIP = registerBlock("terracotta_tip", new WcHopperU(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_ARROW_SLIT = registerBlock("terracotta_arrow_slit", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_ARROW_SLIT_WINDOW = registerBlock("terracotta_arrow_slit_window", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));
    public static final Block TERRACOTTA_ARROW_SLIT_ORNATE = registerBlock("terracotta_arrow_slit_ornate", new WcArrowSlit(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool()));

    private static Block registerBlock(String name, Block block) {
        registerBlockItem(name, block);
        return Registry.register(Registries.BLOCK, new Identifier(Rhumtopia.MOD_ID, name), block);
    }

    private static Item registerBlockItem(String name, Block block) {
        return Registry.register(Registries.ITEM, new Identifier(Rhumtopia.MOD_ID, name),
                new BlockItem(block, new FabricItemSettings()));
    }


    public static void registerModBlocks() {

    }
}
