package com.fal701.block.PannellingCarving;

import com.fal701.Rhumtopia;
import com.fal701.block.MediumAshlar.MediumAshlar;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class WcItemGroupPannellingCarving {
    public static final ItemGroup PANNELLING_CARVING = FabricItemGroup.builder()
            .icon(() -> new ItemStack(PannellingCarving.NORTHERN_CARVINGS))
            .displayName(Text.translatable("itemGroup.WesterosPanellingCarvings"))
            .entries((context, entries) -> {
                entries.add(PannellingCarving.NORTHERN_CARVINGS);
                entries.add(PannellingCarving.NORTHERN_CARVINGS_2);
                entries.add(PannellingCarving.REACH_OAK_WOOD_PANELLING);
                entries.add(PannellingCarving.REACH_OAK_WOOD_PANELLING_WALL);
                entries.add(PannellingCarving.REACH_SPRUCE_WOOD_PANELLING);
                entries.add(PannellingCarving.REACH_SPRUCE_WOOD_PANELLING_WALL);
                entries.add(PannellingCarving.GREY_KEYSTONE);
                entries.add(PannellingCarving.DRAGON_CARVING);
                entries.add(PannellingCarving.WINTERFELL_CARVING);
                entries.add(PannellingCarving.NETHER_BRICK_KEYSTONE);
                entries.add(PannellingCarving.COBBLE_KEYSTONE);
                entries.add(PannellingCarving.SANDSTONE_PILLAR);
                entries.add(PannellingCarving.SMALL_ORANGE_BRICKS_ORNATE);
                entries.add(PannellingCarving.SMALL_ORANGE_BRICKS_ORNATE_TOP);
                entries.add(PannellingCarving.BLUEGREEN_CARVED_SANDSTONE);
                entries.add(PannellingCarving.ORNATE_SANDSTONE);
                entries.add(PannellingCarving.ORNATE_MARBLE);
                entries.add(PannellingCarving.REDORANGE_CARVED_SANDSTONE);
                entries.add(PannellingCarving.FAITH_CARVE_BLACK_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_DARK_GREY_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_BROWN_GREY_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_SMALL_STONE_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_GREY_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_STONE_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_REACH_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_PINK_SANDSTONE);
                entries.add(PannellingCarving.FAITH_CARVE_DUN_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_COARSE_RED_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_OLDTOWN_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_ARBOR_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_WESTERLANDS_BRICK);
                entries.add(PannellingCarving.FAITH_CARVE_STORMLANDS_BRICK);
                entries.add(PannellingCarving.BLACK_BRICK_ENGRAVED);
                entries.add(PannellingCarving.BLACK_BRICK_ENGRAVED_WALL);
                entries.add(PannellingCarving.KL_DUN_CARVED_BRICK);
                entries.add(PannellingCarving.KL_DUN_CARVED_BRICK_WALL);
                entries.add(PannellingCarving.VIVID_DARK_SANDSTONE_ENGRAVED);
                entries.add(PannellingCarving.VIVID_DARK_SANDSTONE_ENGRAVED_WALL);
                entries.add(PannellingCarving.DARK_GREY_BRICK_ENGRAVED);
                entries.add(PannellingCarving.DARK_GREY_BRICK_ENGRAVED_WALL);
                entries.add(PannellingCarving.COARSE_RED_CARVED_SANDSTONE);
                entries.add(PannellingCarving.COARSE_RED_CARVED_SANDSTONE_WALL);
                entries.add(PannellingCarving.MONOCHROME_DARK_SANDSTONE_ENGRAVED);
                entries.add(PannellingCarving.MONOCHROME_DARK_SANDSTONE_ENGRAVED_WALL);
                entries.add(PannellingCarving.GREEN_GREY_BRICK_ENGRAVED);
                entries.add(PannellingCarving.GREEN_GREY_BRICK_ENGRAVED_WALL);
                entries.add(PannellingCarving.COARSE_DARK_RED_CARVED_SANDSTONE);
                entries.add(PannellingCarving.COARSE_DARK_RED_CARVED_SANDSTONE_WALL);
                entries.add(PannellingCarving.DESERT_SANDSTONE_ENGRAVED);
                entries.add(PannellingCarving.DESERT_SANDSTONE_ENGRAVED_WALL);
                entries.add(PannellingCarving.GREY_BRICK_ENGRAVED);
                entries.add(PannellingCarving.GREY_BRICK_ENGRAVED_WALL);
                entries.add(PannellingCarving.ARBOR_BRICK_ORNATE);
                entries.add(PannellingCarving.ARBOR_BRICK_ORNATE_WALL);
                entries.add(PannellingCarving.WHITE_BRICK_ENGRAVED);
                entries.add(PannellingCarving.WHITE_BRICK_ENGRAVED_WALL);
                entries.add(PannellingCarving.VIVID_SANDSTONE_ENGRAVED);
                entries.add(PannellingCarving.VIVID_SANDSTONE_ENGRAVED_WALL);
                entries.add(PannellingCarving.PINK_SANDSTONE_ENGRAVED);
                entries.add(PannellingCarving.PINK_SANDSTONE_ENGRAVED_WALL);
                entries.add(PannellingCarving.MONOCHROME_SANDSTONE_ENGRAVED);
                entries.add(PannellingCarving.MONOCHROME_SANDSTONE_ENGRAVED_WALL);
                entries.add(PannellingCarving.BLACK_GRANITE_POLISHED);
                entries.add(PannellingCarving.BLACK_GRANITE_POLISHED_STAIRS);
                entries.add(PannellingCarving.BLACK_GRANITE_POLISHED_SLAB);
                entries.add(PannellingCarving.BLACK_GRANITE_POLISHED_WALL);
                entries.add(PannellingCarving.WINTERFELL_GRANITE_POLISHED);
                entries.add(PannellingCarving.WINTERFELL_GRANITE_POLISHED_STAIRS);
                entries.add(PannellingCarving.WINTERFELL_GRANITE_POLISHED_SLAB);
                entries.add(PannellingCarving.WINTERFELL_GRANITE_POLISHED_WALL);
                entries.add(PannellingCarving.GREEN_GREY_GRANITE_POLISHED);
                entries.add(PannellingCarving.GREEN_GREY_GRANITE_POLISHED_STAIRS);
                entries.add(PannellingCarving.GREEN_GREY_GRANITE_POLISHED_SLAB);
                entries.add(PannellingCarving.GREEN_GREY_GRANITE_POLISHED_WALL);
                entries.add(PannellingCarving.WHITE_GRANITE_POLISHED);
                entries.add(PannellingCarving.WHITE_GRANITE_POLISHED_STAIRS);
                entries.add(PannellingCarving.WHITE_GRANITE_POLISHED_SLAB);
                entries.add(PannellingCarving.WHITE_GRANITE_POLISHED_WALL);
                entries.add(PannellingCarving.OLDTOWN_GRANITE_POLISHED);
                entries.add(PannellingCarving.OLDTOWN_GRANITE_POLISHED_STAIRS);
                entries.add(PannellingCarving.OLDTOWN_GRANITE_POLISHED_SLAB);
                entries.add(PannellingCarving.OLDTOWN_GRANITE_POLISHED_WALL);
                entries.add(PannellingCarving.VIVID_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.VIVID_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.VIVID_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.VIVID_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.MONOCRHOME_DARK_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.MONOCRHOME_DARK_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.MONOCRHOME_DARK_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.MONOCRHOME_DARK_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.DORNE_DARK_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.DORNE_DARK_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.DORNE_DARK_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.DORNE_DARK_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.DORNE_LIGHT_TERRACOTTA_POLISHED);
                entries.add(PannellingCarving.DORNE_LIGHT_TERRACOTTA_POLISHED_STAIRS);
                entries.add(PannellingCarving.DORNE_LIGHT_TERRACOTTA_POLISHED_SLAB);
                entries.add(PannellingCarving.DORNE_LIGHT_TERRACOTTA_POLISHED_WALL);
                entries.add(PannellingCarving.PINK_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.PINK_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.PINK_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.PINK_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.KL_DUN_BRICK_POLISHED);
                entries.add(PannellingCarving.KL_DUN_BRICK_POLISHED_STAIRS);
                entries.add(PannellingCarving.KL_DUN_BRICK_POLISHED_SLAB);
                entries.add(PannellingCarving.KL_DUN_BRICK_POLISHED_WALL);
                entries.add(PannellingCarving.RED_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.RED_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.RED_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.RED_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.DARK_RED_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.DARK_RED_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.DARK_RED_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.DARK_RED_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.ARBOR_BRICK_POLISHED);
                entries.add(PannellingCarving.ARBOR_BRICK_POLISHED_STAIRS);
                entries.add(PannellingCarving.ARBOR_BRICK_POLISHED_SLAB);
                entries.add(PannellingCarving.ARBOR_BRICK_POLISHED_WALL);
                entries.add(PannellingCarving.VIVID_DARK_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.VIVID_DARK_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.VIVID_DARK_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.VIVID_DARK_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.DESERT_SANDSTONE_POLISHED);
                entries.add(PannellingCarving.DESERT_SANDSTONE_POLISHED_STAIRS);
                entries.add(PannellingCarving.DESERT_SANDSTONE_POLISHED_SLAB);
                entries.add(PannellingCarving.DESERT_SANDSTONE_POLISHED_WALL);
                entries.add(PannellingCarving.DORNE_DULL_TERRACOTTA_POLISHED);
                entries.add(PannellingCarving.DORNE_DULL_TERRACOTTA_POLISHED_STAIRS);
                entries.add(PannellingCarving.DORNE_DULL_TERRACOTTA_POLISHED_SLAB);
                entries.add(PannellingCarving.DORNE_DULL_TERRACOTTA_POLISHED_WALL);
                entries.add(PannellingCarving.TERRACOTTA_POLISHED);
                entries.add(PannellingCarving.TERRACOTTA_POLISHED_STAIRS);
                entries.add(PannellingCarving.TERRACOTTA_POLISHED_SLAB);
                entries.add(PannellingCarving.TERRACOTTA_POLISHED_WALL);
            }).build();

    public static void registerItemGroups() {
        Registry.register(Registries.ITEM_GROUP, new Identifier(Rhumtopia.MOD_ID, "pannelling_carving"), PANNELLING_CARVING);
    }
}
