package com.fal701.block.ClothFibers;

import com.fal701.Rhumtopia;
import com.fal701.block.Lighting.Lighting;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class WcItemGroupClothFibers {
    public static final ItemGroup CLOTHFIBERS = FabricItemGroup.builder()
            .icon(() -> new ItemStack(ClothFibers.BLACK_WOOL))
            .displayName(Text.translatable("itemGroup.WesterosClothFibers"))
            .entries((context, entries) -> {
                entries.add(ClothFibers.CLOTHESLINE);
                entries.add(ClothFibers.VERTICAL_ROPE);
                entries.add(ClothFibers.ROPE_BLOCK_HARNESS);
                entries.add(ClothFibers.ROPE_LADDER);
                entries.add(ClothFibers.VERTICAL_NET);
                entries.add(ClothFibers.HORIZONTAL_ROPE);
                entries.add(ClothFibers.HORIZONTAL_NET);
                entries.add(ClothFibers.FANCY_RED_CARPET);
                entries.add(ClothFibers.FANCY_BLUE_CARPET);
                entries.add(ClothFibers.BLACK_WOOL);
                entries.add(ClothFibers.BLACK_WOOL_STAIRS);
                entries.add(ClothFibers.BLACK_WOOL_SLAB);
                entries.add(ClothFibers.BLACK_WOOL_WALL);
                entries.add(ClothFibers.BLACK_WOOL_FENCE);
                entries.add(ClothFibers.BLACK_WOOL_TIP);
                entries.add(ClothFibers.BLACK_WOOL_CARPET);
                entries.add(ClothFibers.GREY_WOOL);
                entries.add(ClothFibers.GREY_WOOL_STAIRS);
                entries.add(ClothFibers.GREY_WOOL_SLAB);
                entries.add(ClothFibers.GREY_WOOL_WALL);
                entries.add(ClothFibers.GREY_WOOL_FENCE);
                entries.add(ClothFibers.GREY_WOOL_TIP);
                entries.add(ClothFibers.GREY_WOOL_CARPET);
                entries.add(ClothFibers.LIGHT_GREY_WOOL);
                entries.add(ClothFibers.LIGHT_GREY_WOOL_STAIRS);
                entries.add(ClothFibers.LIGHT_GREY_WOOL_SLAB);
                entries.add(ClothFibers.LIGHT_GREY_WOOL_WALL);
                entries.add(ClothFibers.LIGHT_GREY_WOOL_FENCE);
                entries.add(ClothFibers.LIGHT_GREY_WOOL_TIP);
                entries.add(ClothFibers.LIGHT_GREY_WOOL_CARPET);
                entries.add(ClothFibers.WHITE_WOOL);
                entries.add(ClothFibers.WHITE_WOOL_STAIRS);
                entries.add(ClothFibers.WHITE_WOOL_SLAB);
                entries.add(ClothFibers.WHITE_WOOL_WALL);
                entries.add(ClothFibers.WHITE_WOOL_FENCE);
                entries.add(ClothFibers.WHITE_WOOL_TIP);
                entries.add(ClothFibers.WHITE_WOOL_CARPET);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL_STAIRS);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL_SLAB);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL_WALL);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL_FENCE);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL_TIP);
                entries.add(ClothFibers.DIRTY_WHITE_WOOL_CARPET);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL_STAIRS);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL_SLAB);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL_WALL);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL_FENCE);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL_TIP);
                entries.add(ClothFibers.LIGHT_BROWN_WOOL_CARPET);
                entries.add(ClothFibers.BROWN_WOOL);
                entries.add(ClothFibers.BROWN_WOOL_STAIRS);
                entries.add(ClothFibers.BROWN_WOOL_SLAB);
                entries.add(ClothFibers.BROWN_WOOL_WALL);
                entries.add(ClothFibers.BROWN_WOOL_FENCE);
                entries.add(ClothFibers.BROWN_WOOL_TIP);
                entries.add(ClothFibers.BROWN_WOOL_CARPET);
                entries.add(ClothFibers.RED_WOOL);
                entries.add(ClothFibers.RED_WOOL_STAIRS);
                entries.add(ClothFibers.RED_WOOL_SLAB);
                entries.add(ClothFibers.RED_WOOL_WALL);
                entries.add(ClothFibers.RED_WOOL_FENCE);
                entries.add(ClothFibers.RED_WOOL_TIP);
                entries.add(ClothFibers.RED_WOOL_CARPET);
                entries.add(ClothFibers.ORANGE_WOOL);
                entries.add(ClothFibers.ORANGE_WOOL_STAIRS);
                entries.add(ClothFibers.ORANGE_WOOL_SLAB);
                entries.add(ClothFibers.ORANGE_WOOL_WALL);
                entries.add(ClothFibers.ORANGE_WOOL_FENCE);
                entries.add(ClothFibers.ORANGE_WOOL_TIP);
                entries.add(ClothFibers.ORANGE_WOOL_CARPET);
                entries.add(ClothFibers.YELLOW_WOOL);
                entries.add(ClothFibers.YELLOW_WOOL_STAIRS);
                entries.add(ClothFibers.YELLOW_WOOL_SLAB);
                entries.add(ClothFibers.YELLOW_WOOL_WALL);
                entries.add(ClothFibers.YELLOW_WOOL_FENCE);
                entries.add(ClothFibers.YELLOW_WOOL_TIP);
                entries.add(ClothFibers.YELLOW_WOOL_CARPET);
                entries.add(ClothFibers.GREEN_WOOL);
                entries.add(ClothFibers.GREEN_WOOL_STAIRS);
                entries.add(ClothFibers.GREEN_WOOL_SLAB);
                entries.add(ClothFibers.GREEN_WOOL_WALL);
                entries.add(ClothFibers.GREEN_WOOL_FENCE);
                entries.add(ClothFibers.GREEN_WOOL_TIP);
                entries.add(ClothFibers.GREEN_WOOL_CARPET);
                entries.add(ClothFibers.CYAN_WOOL);
                entries.add(ClothFibers.CYAN_WOOL_STAIRS);
                entries.add(ClothFibers.CYAN_WOOL_SLAB);
                entries.add(ClothFibers.CYAN_WOOL_WALL);
                entries.add(ClothFibers.CYAN_WOOL_FENCE);
                entries.add(ClothFibers.CYAN_WOOL_TIP);
                entries.add(ClothFibers.CYAN_WOOL_CARPET);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL_STAIRS);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL_SLAB);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL_WALL);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL_FENCE);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL_TIP);
                entries.add(ClothFibers.LIGHT_BLUE_WOOL_CARPET);
                entries.add(ClothFibers.PURPLE_WOOL);
                entries.add(ClothFibers.PURPLE_WOOL_STAIRS);
                entries.add(ClothFibers.PURPLE_WOOL_SLAB);
                entries.add(ClothFibers.PURPLE_WOOL_WALL);
                entries.add(ClothFibers.PURPLE_WOOL_FENCE);
                entries.add(ClothFibers.PURPLE_WOOL_TIP);
                entries.add(ClothFibers.PURPLE_WOOL_CARPET);
                entries.add(ClothFibers.PINK_WOOL);
                entries.add(ClothFibers.PINK_WOOL_STAIRS);
                entries.add(ClothFibers.PINK_WOOL_SLAB);
                entries.add(ClothFibers.PINK_WOOL_WALL);
                entries.add(ClothFibers.PINK_WOOL_FENCE);
                entries.add(ClothFibers.PINK_WOOL_TIP);
                entries.add(ClothFibers.PINK_WOOL_CARPET);
                entries.add(ClothFibers.LEATHER);
                entries.add(ClothFibers.LEATHER_STAIRS);
                entries.add(ClothFibers.LEATHER_SLAB);
                entries.add(ClothFibers.LEATHER_WALL);
            }).build();

    public static void registerItemGroups() {
        Registry.register(Registries.ITEM_GROUP, new Identifier(Rhumtopia.MOD_ID, "clothfibers"), CLOTHFIBERS);
    }
}
