package com.fal701.block.MarbleAndPlaster;

import com.fal701.Rhumtopia;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class WcItemGroupMarblePlaster {
    public static final ItemGroup MARBLE_PLASTER = FabricItemGroup.builder()
            .icon(() -> new ItemStack(MarblePlaster.MARBLE_PILLAR))
            .displayName(Text.translatable("itemGroup.westerosblocks.marble_paster"))
            .entries((context, entries) -> {
                entries.add(MarblePlaster.MARBLE_PILLAR_VERTICAL_CTM);
                entries.add(MarblePlaster.MARBLE_WALL);
                entries.add(MarblePlaster.MARBLE_PILLAR);
                entries.add(MarblePlaster.THIN_MARBLE_COLUMN);
                entries.add(MarblePlaster.MARBLE_COLUMN_FENCE);//1
                entries.add(MarblePlaster.LANNISPORT_KEYSTONE_YELLOW_PLASTER);
                entries.add(MarblePlaster.LANNISPORT_KEYSTONE_ORANGE_PLASTER);
                entries.add(MarblePlaster.SMALL_SMOOTH_STONE_BRICK_BLUE_PLASTER);
                entries.add(MarblePlaster.SMALL_WHITE_BRICK_BROWNISH_WHITE_PLASTER);
                entries.add(MarblePlaster.SMALL_SMOOTH_STONE_BRICK_WHITE_PLASTER);
                entries.add(MarblePlaster.SMALL_STONE_BRICK_WHITE_PLASTER);
                entries.add(MarblePlaster.SMALL_WHITE_BRICK_WHITE_PLASTER);
                entries.add(MarblePlaster.UNUSED_BROWN_PLASTER);
                entries.add(MarblePlaster.UNUSED_PURPLE_PLASTER);//2
                entries.add(MarblePlaster.QUARTZ);
                entries.add(MarblePlaster.QUARTZ_STAIRS);
                entries.add(MarblePlaster.QUARTZ_SLAB);
                entries.add(MarblePlaster.QUARTZ_WALL);
                entries.add(MarblePlaster.QUARTZ_FENCE);
                entries.add(MarblePlaster.QUARTZ_HOPPER);
                entries.add(MarblePlaster.QUARTZ_TIP);//3
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE);
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE_STAIRS);
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE_SLAB);
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE_WALL);
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE_FENCE);
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE_HOPPER);
                entries.add(MarblePlaster.EYRIE_BLUE_VEINED_MARBLE_TIP);//4
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE);
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE_STAIRS);
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE_SLAB);
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE_WALL);
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE_FENCE);
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE_HOPPER);
                entries.add(MarblePlaster.BAELORS_BROWN_VEINED_MARBLE_TIP);//5
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE_STAIRS);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE_SLAB);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE_WALL);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE_FENCE);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE_HOPPER);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_VEINED_MARBLE_TIP);//6
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE_STAIRS);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE_SLAB);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE_WALL);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE_FENCE);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE_HOPPER);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_MARBLE_TIP);//7
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE);
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE_STAIRS);
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE_SLAB);
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE_WALL);
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE_FENCE);
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE_HOPPER);
                entries.add(MarblePlaster.SUNSPEAR_YELLOW_VEINED_MARBLE_TIP);//8
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE);
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE_STAIRS);
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE_SLAB);
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE_WALL);
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE_FENCE);
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE_HOPPER);
                entries.add(MarblePlaster.STARRY_SEPT_MARBLE_TIP);//9
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE);
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE_STAIRS);
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE_SLAB);
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE_WALL);
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE_FENCE);
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE_HOPPER);
                entries.add(MarblePlaster.CITADEL_GREEN_MARBLE_TIP);//10
                entries.add(MarblePlaster.WHITE_PLASTER);
                entries.add(MarblePlaster.WHITE_PLASTER_STAIRS);
                entries.add(MarblePlaster.WHITE_PLASTER_SLAB);
                entries.add(MarblePlaster.WHITE_PLASTER_WALL);
                entries.add(MarblePlaster.WHITE_PLASTER_FENCE);
                entries.add(MarblePlaster.WHITE_PLASTER_HOPPER);
                entries.add(MarblePlaster.WHITE_PLASTER_TIP);//11.1
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH);
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.WHITE_PLASTER_ROUGH_TIP);//11.2
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_STAIRS);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_SLAB);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_WALL);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_FENCE);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_HOPPER);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_TIP);//12.1
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH_STAIRS);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH_SLAB);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH_WALL);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH_FENCE);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH_HOPPER);
                entries.add(MarblePlaster.PLAIN_WHITE_DAUB_ROUGH_TIP);//13.2
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_STAIRS);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_SLAB);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_WALL);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_FENCE);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_HOPPER);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_TIP);//14.1
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.BROWNISH_WHITE_PLASTER_ROUGH_TIP);//14.2
                entries.add(MarblePlaster.PALE_WHITE_PLASTER);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_STAIRS);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_SLAB);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_WALL);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_FENCE);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_HOPPER);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_TIP);//15.1
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.PALE_WHITE_PLASTER_ROUGH_TIP);//15.2
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_STAIRS);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_SLAB);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_WALL);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_FENCE);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_HOPPER);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_TIP);//16.1
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.YELLOWISH_WHITE_PLASTER_ROUGH_TIP);//16.2
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_STAIRS);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_SLAB);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_WALL);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_FENCE);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_HOPPER);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_TIP);//17.1
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.GREYISH_WHITE_PLASTER_ROUGH_TIP);//17.2
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_STAIRS);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_SLAB);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_WALL);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_FENCE);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_HOPPER);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_TIP);//18.1
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.LIGHT_GREY_PLASTER_ROUGH_TIP);//18.2
                entries.add(MarblePlaster.DARK_GREY_PLASTER);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_STAIRS);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_SLAB);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_WALL);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_FENCE);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_HOPPER);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_TIP);//19.1
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.DARK_GREY_PLASTER_ROUGH_TIP);//19.2
                entries.add(MarblePlaster.LIGHT_RED_PLASTER);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_STAIRS);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_SLAB);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_WALL);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_FENCE);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_HOPPER);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_TIP);//20.1
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.LIGHT_RED_PLASTER_ROUGH_TIP);//20.2
                entries.add(MarblePlaster.RED_PLASTER);
                entries.add(MarblePlaster.RED_PLASTER_STAIRS);
                entries.add(MarblePlaster.RED_PLASTER_SLAB);
                entries.add(MarblePlaster.RED_PLASTER_WALL);
                entries.add(MarblePlaster.RED_PLASTER_FENCE);
                entries.add(MarblePlaster.RED_PLASTER_HOPPER);
                entries.add(MarblePlaster.RED_PLASTER_TIP);//21.1
                entries.add(MarblePlaster.RED_PLASTER_ROUGH);
                entries.add(MarblePlaster.RED_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.RED_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.RED_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.RED_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.RED_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.RED_PLASTER_ROUGH_TIP);//21.2
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_STAIRS);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_SLAB);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_WALL);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_FENCE);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_HOPPER);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_TIP);//22.1
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.CASTERLY_ROCK_CRIMSON_PLASTER_ROUGH_TIP);//22.2
                entries.add(MarblePlaster.DARK_RED_PLASTER);
                entries.add(MarblePlaster.DARK_RED_PLASTER_STAIRS);
                entries.add(MarblePlaster.DARK_RED_PLASTER_SLAB);
                entries.add(MarblePlaster.DARK_RED_PLASTER_WALL);
                entries.add(MarblePlaster.DARK_RED_PLASTER_FENCE);
                entries.add(MarblePlaster.DARK_RED_PLASTER_HOPPER);
                entries.add(MarblePlaster.DARK_RED_PLASTER_TIP);//23.1
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH);
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.DARK_RED_PLASTER_ROUGH_TIP);//23.2
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_STAIRS);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_SLAB);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_WALL);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_FENCE);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_HOPPER);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_TIP);//24.1
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.LANNISPORT_ORANGE_PLASTER_ROUGH_TIP);//24.2
                entries.add(MarblePlaster.ORANGE_PLASTER);
                entries.add(MarblePlaster.ORANGE_PLASTER_STAIRS);
                entries.add(MarblePlaster.ORANGE_PLASTER_SLAB);
                entries.add(MarblePlaster.ORANGE_PLASTER_WALL);
                entries.add(MarblePlaster.ORANGE_PLASTER_FENCE);
                entries.add(MarblePlaster.ORANGE_PLASTER_HOPPER);
                entries.add(MarblePlaster.ORANGE_PLASTER_TIP);//25.1
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH);
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.ORANGE_PLASTER_ROUGH_TIP);//25.2
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_STAIRS);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_SLAB);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_WALL);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_FENCE);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_HOPPER);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_TIP);//26.1
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.DARK_ORANGE_PLASTER_ROUGH_TIP);//26.2
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_STAIRS);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_SLAB);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_WALL);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_FENCE);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_HOPPER);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_TIP);//27.1
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.LANNISPORT_YELLOW_PLASTER_ROUGH_TIP);//27.2
                entries.add(MarblePlaster.DORNE_MUD_PLASTER);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_STAIRS);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_SLAB);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_WALL);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_FENCE);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_HOPPER);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_TIP);//28.1
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.DORNE_MUD_PLASTER_ROUGH_TIP);//28.2
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_STAIRS);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_SLAB);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_WALL);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_FENCE);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_HOPPER);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_TIP);//29.1
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.PALE_YELLOW_PLASTER_ROUGH_TIP);//29.2
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_STAIRS);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_SLAB);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_WALL);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_FENCE);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_HOPPER);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_TIP);//30.1
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.DORNE_DARK_MUD_PLASTER_ROUGH_TIP);//30.2
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_STAIRS);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_SLAB);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_WALL);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_FENCE);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_HOPPER);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_TIP);//31.1
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.ARBOR_BROWN_PLASTER_ROUGH_TIP);//31.2
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_STAIRS);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_SLAB);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_WALL);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_FENCE);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_HOPPER);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_TIP);//32.1
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH_STAIRS);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH_SLAB);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH_WALL);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH_FENCE);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH_HOPPER);
                entries.add(MarblePlaster.PLAIN_BROWN_DAUB_ROUGH_TIP);//32.2
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_STAIRS);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_SLAB);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_WALL);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_FENCE);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_HOPPER);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_TIP);//33.1
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.GULLTOWN_GREEN_PLASTER_ROUGH_TIP);//33.2
                entries.add(MarblePlaster.GREEN_PLASTER);
                entries.add(MarblePlaster.GREEN_PLASTER_STAIRS);
                entries.add(MarblePlaster.GREEN_PLASTER_SLAB);
                entries.add(MarblePlaster.GREEN_PLASTER_WALL);
                entries.add(MarblePlaster.GREEN_PLASTER_FENCE);
                entries.add(MarblePlaster.GREEN_PLASTER_HOPPER);
                entries.add(MarblePlaster.GREEN_PLASTER_TIP);//34.1
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH);
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.GREEN_PLASTER_ROUGH_TIP);//34.2
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_STAIRS);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_SLAB);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_WALL);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_FENCE);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_HOPPER);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_TIP);//35.1
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.HIGHGARDEN_GREEN_PLASTER_ROUGH_TIP);//35.2
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_STAIRS);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_SLAB);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_WALL);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_FENCE);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_HOPPER);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_TIP);//36.1
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.GULLTOWN_BLUE_PLASTER_ROUGH_TIP);//36.2
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_STAIRS);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_SLAB);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_WALL);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_FENCE);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_HOPPER);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_TIP);//37.1
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.LIGHT_BLUE_PLASTER_ROUGH_TIP);//37.2
                entries.add(MarblePlaster.BLUE_PLASTER);
                entries.add(MarblePlaster.BLUE_PLASTER_STAIRS);
                entries.add(MarblePlaster.BLUE_PLASTER_SLAB);
                entries.add(MarblePlaster.BLUE_PLASTER_WALL);
                entries.add(MarblePlaster.BLUE_PLASTER_FENCE);
                entries.add(MarblePlaster.BLUE_PLASTER_HOPPER);
                entries.add(MarblePlaster.BLUE_PLASTER_TIP);//38.1
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH);
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.BLUE_PLASTER_ROUGH_TIP);//38.2
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_STAIRS);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_SLAB);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_WALL);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_FENCE);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_HOPPER);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_TIP);//39.1
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.LIGHT_PURPLE_PLASTER_ROUGH_TIP);//39.2
                entries.add(MarblePlaster.PURPLE_PLASTER);
                entries.add(MarblePlaster.PURPLE_PLASTER_STAIRS);
                entries.add(MarblePlaster.PURPLE_PLASTER_SLAB);
                entries.add(MarblePlaster.PURPLE_PLASTER_WALL);
                entries.add(MarblePlaster.PURPLE_PLASTER_FENCE);
                entries.add(MarblePlaster.PURPLE_PLASTER_HOPPER);
                entries.add(MarblePlaster.PURPLE_PLASTER_TIP);//40.1
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH);
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.PURPLE_PLASTER_ROUGH_TIP);//40.2
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_STAIRS);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_SLAB);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_WALL);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_FENCE);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_HOPPER);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_TIP);//41.1
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.PALE_PURPLE_PLASTER_ROUGH_TIP);//41.2
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_STAIRS);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_SLAB);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_WALL);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_FENCE);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_HOPPER);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_TIP);//42.1
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.HIGHGARDEN_PINK_PLASTER_ROUGH_TIP);//42.2
                entries.add(MarblePlaster.PINK_PLASTER);
                entries.add(MarblePlaster.PINK_PLASTER_STAIRS);
                entries.add(MarblePlaster.PINK_PLASTER_SLAB);
                entries.add(MarblePlaster.PINK_PLASTER_WALL);
                entries.add(MarblePlaster.PINK_PLASTER_FENCE);
                entries.add(MarblePlaster.PINK_PLASTER_HOPPER);
                entries.add(MarblePlaster.PINK_PLASTER_TIP);//43.1
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH);
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.PINK_PLASTER_ROUGH_TIP);//43.2
                entries.add(MarblePlaster.PALE_PINK_PLASTER);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_STAIRS);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_SLAB);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_WALL);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_FENCE);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_HOPPER);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_TIP);//44.1
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH_STAIRS);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH_SLAB);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH_WALL);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH_FENCE);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH_HOPPER);
                entries.add(MarblePlaster.PALE_PINK_PLASTER_ROUGH_TIP);//44.2

            }).build();

    public static void registerItemGroups() {
        Registry.register(Registries.ITEM_GROUP, new Identifier(Rhumtopia.MOD_ID, "marble_plaster"), MARBLE_PLASTER);
    }
}

