package com.fal701;

import com.fal701.block.Brick.Brick;
import com.fal701.block.Fieldstone.Fieldstone;
import com.fal701.block.HalfAshlar.HalfAshlar;
import com.fal701.block.MediumAshlar.MediumAshlar;
import com.fal701.block.QuarterAshlar.QuarterAshlar;
import com.fal701.block.SmoothAshlar.SmoothAshlar;
import com.fal701.block.TimberFrame.TimberFrame;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.render.RenderLayer;

public class RhumtopiaClient implements ClientModInitializer {
    @Override
    public void onInitializeClient() {











//All transparent blocks
        //Fieldstone
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.FAINT_BROWN_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.FAINT_BROWN_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.FAINT_BROWN_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//1
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LIGHT_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LIGHT_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LIGHT_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//2
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.REACH_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.REACH_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.REACH_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//3
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.BROWN_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.BROWN_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.BROWN_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//4
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.FAINT_LIGHT_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.FAINT_LIGHT_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.FAINT_LIGHT_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//5
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.WHITE_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.WHITE_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.WHITE_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//6
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.PALE_PINK_FAINT_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.PALE_PINK_FAINT_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.PALE_PINK_FAINT_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//7
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.PALE_PINK_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.PALE_PINK_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.PALE_PINK_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//8
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.SANDY_PINK_FAINT_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.SANDY_PINK_FAINT_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.SANDY_PINK_FAINT_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//9
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.SANDY_PINK_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.SANDY_PINK_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.SANDY_PINK_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//10
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LIGHT_OLDTOWN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LIGHT_OLDTOWN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LIGHT_OLDTOWN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//11
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.OLDTOWN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.OLDTOWN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.OLDTOWN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//12
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.ARBOR_SMALL_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.ARBOR_SMALL_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.ARBOR_SMALL_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//13
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LANNISPORT_LIGHT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LANNISPORT_LIGHT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Fieldstone.LANNISPORT_LIGHT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//14

        //Smooth Ashlar
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.BLACK_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.BLACK_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.BLACK_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//1
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.BROWN_GREY_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.BROWN_GREY_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.BROWN_GREY_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//2
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.GREY_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.GREY_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.GREY_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//3
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//4
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.WHITE_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.WHITE_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.WHITE_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//5
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//6
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.PALE_PINK_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.PALE_PINK_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.PALE_PINK_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//7
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.RED_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.RED_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.RED_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//8
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.DARK_RED_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.DARK_RED_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.DARK_RED_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//9
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.OLDTOWN_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.OLDTOWN_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.OLDTOWN_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//10
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.ARBOR_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.ARBOR_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.ARBOR_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//11
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.LANNISPORT_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.LANNISPORT_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.LANNISPORT_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//12
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.STORMLANDS_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.STORMLANDS_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.STORMLANDS_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//13
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.TERRACOTTA_LIGHT_STONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.TERRACOTTA_LIGHT_STONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(SmoothAshlar.TERRACOTTA_LIGHT_STONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//10

        //Quarter Ashlar
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.BASALT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.BASALT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.BASALT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//1
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_DARK_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_DARK_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_DARK_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//2
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_BROWN_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_BROWN_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_BROWN_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//3
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_BROWN_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_BROWN_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_BROWN_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//4
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_STONE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_STONE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_STONE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//5
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_STONE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_STONE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_STONE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//6
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_FAINT_LIGHT_GREY_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_FAINT_LIGHT_GREY_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_FAINT_LIGHT_GREY_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//7
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_WHITE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_WHITE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_WHITE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//8
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.REACH_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.REACH_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.REACH_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//9
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SANDY_PINK_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SANDY_PINK_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SANDY_PINK_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//10
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_KL_DUN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_KL_DUN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_KL_DUN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//11
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_COARSE_RED_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_COARSE_RED_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_COARSE_RED_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//12
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.UNUSED_PURPLE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.UNUSED_PURPLE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.UNUSED_PURPLE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//13
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.DARK_RED_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.DARK_RED_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.DARK_RED_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//14
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_OLDTOWN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_OLDTOWN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_OLDTOWN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//15
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_OLDTOWN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_OLDTOWN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_OLDTOWN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//16
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_ARBOR_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_ARBOR_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_ARBOR_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//17
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_LANNISPORT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_LANNISPORT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_SMOOTH_LANNISPORT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//18
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_LANNISPORT_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_LANNISPORT_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_LANNISPORT_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//19
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.UNUSED_BROWN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.UNUSED_BROWN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.UNUSED_BROWN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//20
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.STORMLANDS_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.STORMLANDS_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.STORMLANDS_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//21
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_TERRACOTTA_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_TERRACOTTA_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(QuarterAshlar.SMALL_TERRACOTTA_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());//22

        //Medium Ashlar
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.BLACK_GRANITE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.BLACK_GRANITE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.BLACK_GRANITE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.WINTERFELL_GRANITE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.WINTERFELL_GRANITE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.WINTERFELL_GRANITE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.KL_DUN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.KL_DUN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.KL_DUN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.COARSE_RED_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.COARSE_RED_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.COARSE_RED_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.RED_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.RED_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.RED_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.GREEN_GREY_GRANITE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.GREEN_GREY_GRANITE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.GREEN_GREY_GRANITE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.WHITE_GRANITE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.WHITE_GRANITE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.WHITE_GRANITE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.PINK_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.PINK_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.PINK_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.MONOCHROME_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.MONOCHROME_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.MONOCHROME_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.VIVID_DARK_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.VIVID_DARK_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.VIVID_DARK_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.MONOCHROME_DARK_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.MONOCHROME_DARK_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.MONOCHROME_DARK_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DESERT_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DESERT_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DESERT_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.COARSE_DARK_RED_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.COARSE_DARK_RED_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.COARSE_DARK_RED_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DARK_RED_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DARK_RED_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DARK_RED_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.OLDTOWN_GRANITE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.OLDTOWN_GRANITE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.OLDTOWN_GRANITE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.ARBOR_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.ARBOR_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.ARBOR_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.VIVID_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.VIVID_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.VIVID_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_DARK_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_DARK_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_DARK_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_DULL_TERRACOTTA_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_DULL_TERRACOTTA_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_DULL_TERRACOTTA_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_LIGHT_TERRACOTTA_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_LIGHT_TERRACOTTA_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.DORNE_LIGHT_TERRACOTTA_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.TERRACOTTA_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.TERRACOTTA_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(MediumAshlar.TERRACOTTA_ARROW_SLIT_ORNATE, RenderLayer.getCutout());

        //HALF ASHLAR
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.NETHER_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.NETHER_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.NETHER_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.DARK_GREY_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.DARK_GREY_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.DARK_GREY_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.BROWN_GREY_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.BROWN_GREY_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.BROWN_GREY_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.GREEN_GREY_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.GREEN_GREY_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.GREEN_GREY_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STONE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STONE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STONE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.MOSSY_STONE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.MOSSY_STONE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.MOSSY_STONE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.FAINT_LIGHT_GREY_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.FAINT_LIGHT_GREY_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.FAINT_LIGHT_GREY_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STONE_SLAB_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STONE_SLAB_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STONE_SLAB_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.REACH_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.REACH_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.REACH_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.SANDY_PINK_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.SANDY_PINK_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.SANDY_PINK_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.KL_DUN_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.KL_DUN_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.KL_DUN_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.COARSE_RED_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.COARSE_RED_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.COARSE_RED_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.OLDTOWN_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.OLDTOWN_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.OLDTOWN_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.ARBOR_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.ARBOR_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.ARBOR_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.LARGE_BRICK_SANDSTONE_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.LARGE_BRICK_SANDSTONE_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.LARGE_BRICK_SANDSTONE_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STORMLANDS_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STORMLANDS_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.STORMLANDS_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.TERRACOTTA_LARGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.TERRACOTTA_LARGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(HalfAshlar.TERRACOTTA_LARGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());

        //BRICK
        BlockRenderLayerMap.INSTANCE.putBlock(Brick.SMALL_ORANGE_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Brick.SMALL_ORANGE_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Brick.SMALL_ORANGE_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Brick.SOUTHERN_BRICK_ARROW_SLIT, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Brick.SOUTHERN_BRICK_ARROW_SLIT_WINDOW, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(Brick.SOUTHERN_BRICK_ARROW_SLIT_ORNATE, RenderLayer.getCutout());

        //TIMBER FRAME
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_BROWN_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_WHITE_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRICK_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_OLDTOWN_BRICK_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_YELLOW_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_ORANGE_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_OAK_LANNISPORT_BRICK_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BROWN_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_WHITE_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_ORANGE_BRICK_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREY_BRICK_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_RED_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_PALE_YELLOW_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_BLUE_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_NORTHERN_GREEN_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_WHITEWASHED_BRESSUMMER, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_CROSSHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_LEFTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_RIGHTHATCH, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_FRAME, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_VERTICAL, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_CLOSE_STUDDING, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_LEFTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_RIGHTHATCH_LARGE, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_LEFTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_RIGHTHATCH_STUDDED, RenderLayer.getCutout());
        BlockRenderLayerMap.INSTANCE.putBlock(TimberFrame.TIMBER_RED_WHITE_BRESSUMMER, RenderLayer.getCutout());
    }
}
