package com.fal701.block.SmoothAshlar;

import com.fal701.Rhumtopia;
import com.fal701.block.Fieldstone.Fieldstone;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class WcItemGroupSmoothAshlar {
    public static final ItemGroup SMOOTH_ASHLAR = FabricItemGroup.builder()
            .icon(() -> new ItemStack(SmoothAshlar.GREY_LIGHT_STONE))
            .displayName(Text.translatable("itemGroup.WesterosSmoothAshlar"))
            .entries((context, entries) -> {
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.BLACK_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.BROWN_GREY_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.GREY_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.FAINT_LIGHT_GREY_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.WHITE_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.LIGHT_STONE);
                entries.add(SmoothAshlar.LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.PALE_PINK_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.RED_LIGHT_STONE);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.RED_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.DARK_RED_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.OLDTOWN_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.ARBOR_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.LANNISPORT_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.STORMLANDS_LIGHT_STONE_ARROW_SLIT_ORNATE);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_STAIRS);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_SLAB);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_WALL);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_FENCE);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_HOPPER);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_TIP);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_ARROW_SLIT);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_ARROW_SLIT_WINDOW);
                entries.add(SmoothAshlar.TERRACOTTA_LIGHT_STONE_ARROW_SLIT_ORNATE);
            }).build();

    public static void registerItemGroups() {
        Registry.register(Registries.ITEM_GROUP, new Identifier(Rhumtopia.MOD_ID, "smooth_ashlar"), SMOOTH_ASHLAR);
    }
}




